on: [push]

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/toolchain@v1
        with:
          toolchain: 1.77.2
          target: wasm32-unknown-unknown
          override: true
          components: clippy
      - run: cargo install wasm-pack --version 0.9.1
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i --frozen-lockfile
      - run: pnpm build